{
  imports = [
    ./atuin.nix
    ./devenv.nix
    ./direnv.nix
    ./email.nix
    ./fcitx5
    ./firefox
    ./git.nix
    ./gpg.nix
    ./im.nix
    ./kooha.nix
    ./mpv.nix
    ./music
    ./neofetch
    ./neovide.nix
    ./nix-index.nix
    ./obs.nix
    ./resource_monitor
    ./utils.nix
    ./ssh.nix
    ./wemeet.nix
    ./yesplaymusic.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zoxide.nix
  ];
}
